:errbit:
  :projects:
    :project_1:
      :api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    :project_2:
      :api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  :base_uri: "https://errbit.example.com"
  :date_format: "%d/%m %H:%M"
:newrelic:
  :api_key: "xxxxxxxxxxxxxxx"
  :app_name: 'Your App Name'
:gocd:
  :url: 'http://go:8153/go/cctray.xml'
